<a href="https://colab.research.google.com/github/DOOBIDOOBI/LinearAlgebra_2ndSem/blob/main/Assignment6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline


#Transition

In [2]:
A = np.array([
              [2,3,4],
              [5,3,2],
              [7,9,3]
])
A

array([[2, 3, 4],
       [5, 3, 2],
       [7, 9, 3]])

In [4]:
A = np.transpose ([[2, 3, 4],
       [5, 3, 2],
       [7, 9, 3]])
A

array([[2, 5, 7],
       [3, 3, 9],
       [4, 2, 3]])

In [5]:
B = np. array ([
                [9,2,3],
                [21,3,6],
                [3,4,5]
])

$$
A = 
    \begin{bmatrix}
        x & y \\ 
        4x & 10y
    \end{bmatrix}
 $$

$$
B=\begin{bmatrix} 1 & 2 & 5 \\5 & -1 & 0 \\ 0 & -3 & 3\end{bmatrix}\\
$$

In [6]:
A @ B

array([[144,  47,  71],
       [117,  51,  72],
       [ 87,  26,  39]])

In [7]:
A.dot (B)

array([[144,  47,  71],
       [117,  51,  72],
       [ 87,  26,  39]])

$$
P=\begin{bmatrix} 41 & 22 & 58 \\55 & -12 & 40 \\ 60 & -53 & 23\\23 & 45 & 86\end{bmatrix}\\
$$

$$
B=\begin{bmatrix} 1 & 2 & 5 \\5 & -1 & 0 \\ 0 & -3 & 3\end{bmatrix}\\
$$
$$
T=\begin{bmatrix} 12 & 23 & 50\\12 & 45 & 12\\12 & 87 & 45\\ 90 & 123 & 23\end{bmatrix}\\
$$

 1. $A \cdot B \neq B \cdot A$
 2. $A \cdot (B \cdot C) = (A \cdot B) \cdot C$
 3. $A\cdot(B+C) = A\cdot B + A\cdot C$
 4. $(B+C)\cdot A = B\cdot A + C\cdot A$
 5. $A\cdot I = A$
 6. $A\cdot \emptyset = \emptyset$


In [28]:
P = np.array([
              [23, 65, 78, 45],
              [56, 32, 34, 56],
              [65, 78, 34, 78],
              [54, 87, 89, 99]
])

B = np.array ([ 
               [32, 56, 897, 45],
               [10, 54, 65, 45],
               [87, 98, 67, 12],
               [45, 87, 89, 65]
])

T = np.array ([ 
               [12, 65, 8, 3],
               [7, 98, 21, 65],
               [4, 56, 35, 45], 
               [87, 9, 45, 6]
])

In [13]:
P @ B

array([[10197, 16357, 34087,  7821],
       [ 7590, 13068, 59574,  8008],
       [ 9328, 17970, 72595, 11913],
       [14796, 25057, 68867, 13848]])

In [14]:
B @ P

array([[64607, 77753, 38903, 78997],
       [ 9909, 11363,  8831, 12999],
       [12492, 15061, 13464, 15817],
       [15202, 18306, 15279, 20274]])

In [15]:
np.array_equiv(B @ P, P @ B)

False

In [16]:
P @ (B @ T)

array([[1053638, 4245052, 1970063, 2674637],
       [1117548, 5182230, 2780598, 3601068],
       [1564537, 6539917, 3528904, 4534287],
       [1833195, 7398510, 3678070, 4855196]])

In [17]:
(P@B)@T

array([[1053638, 4245052, 1970063, 2674637],
       [1117548, 5182230, 2780598, 3601068],
       [1564537, 6539917, 3528904, 4534287],
       [1833195, 7398510, 3678070, 4855196]])

In [19]:
np.array_equiv((P @ B) @ T,P @ (B @ T) )

True

In [20]:
P @ (B + T)

array([[15155, 28995, 40391, 15895],
       [13494, 22252, 64404, 12122],
       [17576, 32445, 79453, 19176],
       [25022, 42968, 78696, 24264]])

In [21]:
P @ B + P @ T

array([[15155, 28995, 40391, 15895],
       [13494, 22252, 64404, 12122],
       [17576, 32445, 79453, 19176],
       [25022, 42968, 78696, 24264]])

In [22]:
np.array_equiv(P @ (B + T), P @ B + P @ T)

True

In [23]:
P.dot(1)

array([[23, 65, 78, 45],
       [56, 32, 34, 56],
       [65, 78, 34, 78],
       [54, 87, 89, 99]])

In [24]:
P

array([[23, 65, 78, 45],
       [56, 32, 34, 56],
       [65, 78, 34, 78],
       [54, 87, 89, 99]])

In [25]:
np.array_equiv(P.dot(1), P)

True

In [35]:
P.dot(0)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [36]:
np.array_equiv(P.dot(0), 0)

True

In [37]:
K = np.array([
              [21,45],
              [48,54]
])


np.linalg.det(K)

-1026.0

In [34]:
J = np.array ([ 
               [32, 56, 897],
               [10, 54, 65],
               [87, 98, 67]
              
])
np.linalg.det(J)

-3143949.9999999963

In [44]:
O = np.array([
              [21,45,90],
              [48,54,9],
              [4, 5, 6]
])
np.array(O @ np.linalg.inv(O), dtype=int)

array([[1, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [42]:
Q = np.array([
              [2, 1, 5, 4],
              [48,54, 9, 5],
              [45, 98, 4, 3],
              [87, 5, 4, 6]
])
np.array(Q @ np.linalg.inv(Q),dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])