<a href="https://colab.research.google.com/github/DOOBIDOOBI/LinearAlgebra_2ndSem/blob/main/Assignment3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Linear Algebra for ChE
##Laboratory 4: Matrices

###

###Objectives:



#Discussion

In [1]:
import numpy as np
import matplotlib as plt
import scipy.linalg as la
%matplotlib inline 

##Matrices

The notation and use of matrices is probably one of the fundamentals of modern computing. Matrices are also handy representations of complex equations or mintiple inter-related equatios fron 2-dimensional equations to even hundred and thousands of them. 


Let say for example you have A and B as sustem of equation.

$$
A = \left\{
    \begin{array}\
        x + y \\ 
        4x - 10y
    \end{array}
\right. \\
B = \left\{
    \begin{array}\
        x+y+z \\ 
        3x -2y -z \\
        -x + 4y +2z
    \end{array}
\right. \\
C = \left\{
    \begin{array}\
        x+y+z \\ 
        3x -2y -z \\
        -x + 4y +2z
    \end{array}
\right. $$


We could see that A is a system of 2 equations with 2 parameters. While B is a system of 3 equations with 3 parameters. We can represent them as matrices as:

:$$
A=\begin{bmatrix} 1 & 1 \\ 4 & {-10}\end{bmatrix} \\
B=\begin{bmatrix} 1 & 1 & 1 \\ 3 & -2 & -1 \\ -1 & 4 & 2\end{bmatrix}\\
C=\begin{bmatrix} 1 & -2 &  3 & -4\\ 3 & -1 & -2&  1\\ 2 & -1 &  3 & -2\end{bmatrix}
$$


$$A=\begin{bmatrix}
a_{(0,0)}&a_{(0,1)}&\dots&a_{(0,j-1)}\\
a_{(1,0)}&a_{(1,1)}&\dots&a_{(1,j-1)}\\
\vdots&\vdots&\ddots&\vdots&\\
a_{(i-1,0)}&a_{(i-1,1)}&\dots&a_{(i-1,j-1)}
\end{bmatrix}
$$


In [14]:
def describe_mat(matrix):
    print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\n')

In [15]:
## Declaring a 2x2 matrix
A = np.array([
    [2, 3],
    [5, 4]
])
describe_mat (A)

Matrix:
[[2 3]
 [5 4]]

Shape:	(2, 2)
Rank:	2



In [16]:
F = np.array([
    [2, 3, 4],
    [3, 4, 3]
])
describe_mat(F)

Matrix:
[[2 3 4]
 [3 4 3]]

Shape:	(2, 3)
Rank:	2



In [17]:
H = np.array([1, 2, 3, 4, 5])
describe_mat(H)

Matrix:
[1 2 3 4 5]

Shape:	(5,)
Rank:	1



#Categorizing Matrices
##


Row and colums matrices are common inn vector and matrix computation. They can also represent row

In [19]:
kikiam = np.array([
    1, 3, 2, 4
])
fishball = np.array([
    [1,2,3,4]
])
describe_mat(kikiam)
describe_mat(fishball)


Matrix:
[1 3 2 4]

Shape:	(4,)
Rank:	1

Matrix:
[[1 2 3 4]]

Shape:	(1, 4)
Rank:	2



In [22]:
kwek2x = np.array([
    [1],
    [2],
    [3],
    [4]
])
describe_mat(kwek2x)

Matrix:
[[1]
 [2]
 [3]
 [4]]

Shape:	(4, 1)
Rank:	2



In [24]:
def describe_mat(matrix):
      is_square = True if matrix.shape[0] == matrix.shape[1] else False
      print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\nIs Square:{is_square}\n')

In [29]:
box = np.array([
    [1,3,5,1,2,4,5,6,7,8],
    [1,3,5,1,2,4,5,6,7,8],
    [1,3,5,1,2,4,5,6,7,8],
    [1,3,5,1,2,4,5,6,7,8],
    [1,3,5,1,2,4,5,6,7,8],
    [1,3,5,1,2,4,5,6,7,8],
    [1,3,5,1,2,4,5,6,7,8],
    [1,3,5,1,2,4,5,6,7,8],
    [1,3,5,1,2,4,5,6,7,8],
    [1,3,5,1,2,4,5,6,7,8]
    
])
chocolatebar = np.array([
    [3,5,6],
    [3,5,6],
    [3,5,6],
    [3,5,6],
    [3,5,6],
    [3,5,6],
    [3,5,6],
    [3,5,6],
    [3,5,6],
    [3,5,6],
    [3,5,6],
    [3,5,6],
    [3,5,6],
    [3,5,6],
    [3,5,6],
    [3,5,6],
    [1,4,6]
])
describe_mat(box)
describe_mat(chocolatebar)

Matrix:
[[1 3 5 1 2 4 5 6 7 8]
 [1 3 5 1 2 4 5 6 7 8]
 [1 3 5 1 2 4 5 6 7 8]
 [1 3 5 1 2 4 5 6 7 8]
 [1 3 5 1 2 4 5 6 7 8]
 [1 3 5 1 2 4 5 6 7 8]
 [1 3 5 1 2 4 5 6 7 8]
 [1 3 5 1 2 4 5 6 7 8]
 [1 3 5 1 2 4 5 6 7 8]
 [1 3 5 1 2 4 5 6 7 8]]

Shape:	(10, 10)
Rank:	2
Is Square:True

Matrix:
[[3 5 6]
 [3 5 6]
 [3 5 6]
 [3 5 6]
 [3 5 6]
 [3 5 6]
 [3 5 6]
 [3 5 6]
 [3 5 6]
 [3 5 6]
 [3 5 6]
 [3 5 6]
 [3 5 6]
 [3 5 6]
 [3 5 6]
 [3 5 6]
 [1 4 6]]

Shape:	(17, 3)
Rank:	2
Is Square:False



##Null Matrix

In [30]:
def describe_mat(matrix):
  if matrix.size > 0:
      is_square = True if matrix.shape[0] == matrix.shape[1] else False
      print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\nIs Square:{is_square}\n')
  else:
      print('matrix is null')

In [35]:
null = np.array([])
describe_mat
notnull = np.array([
    [1,2],
    [1,2]
])
describe_mat(null)
describe_mat(notnull)

matrix is null
Matrix:
[[1 2]
 [1 2]]

Shape:	(2, 2)
Rank:	2
Is Square:True



In [45]:
row = np.zeros((2,3))
box = np.zeros((3,3))
rect = np.zeros((3,2))

print(f'Zero Row Matrix: \n{row}')
print(f'Zero Square Matrix: \n{box}')
print(f'Zero Rectangular Matrix: \n{rect}')

Zero Row Matrix: 
[[0. 0. 0.]
 [0. 0. 0.]]
Zero Square Matrix: 
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Zero Rectangular Matrix: 
[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [43]:
ones_mat_row = np.ones((2,3))
ones_mat_sqr = np.ones((3,3))
ones_mat_rct = np.ones((3,2))

print(f'Ones Row Matrix: \n{ones_mat_row}')
print(f'Ones Square Matrix: \n{ones_mat_sqr}')
print(f'Ones Rectangular Matrix: \n{ones_mat_rct}')

Ones Row Matrix: 
[[1. 1. 1.]
 [1. 1. 1.]]
Ones Square Matrix: 
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Ones Rectangular Matrix: 
[[1. 1.]
 [1. 1.]
 [1. 1.]]


#Diagonal Matrix

In [47]:
np.array([
          [1,0,0],
          [0,1,0],
          [0,0,1]
])

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [49]:
padiagonal = np.diag([1,2,3,4,5,6,])
padiagonal.shape[0] == padiagonal.shape[1]
padiagonal

array([[1, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0],
       [0, 0, 0, 4, 0, 0],
       [0, 0, 0, 0, 5, 0],
       [0, 0, 0, 0, 0, 6]])

#Identity Matrix
##### An identity matrix is a special diagonal matrix in which the values at the diagonal are ones

In [51]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [52]:
np.identity(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

#Upper Triangular Matrix

####An uppertriangular matrix is a matrix that has no values below the diagonal

In [53]:
np.array([
          [1,2,3],
          [0,1,2],
          [0,0,2]
])

array([[1, 2, 3],
       [0, 1, 2],
       [0, 0, 2]])

In [54]:
np.array([
          [1,0,0],
          [1,1,0],
          [3,1,2]
])

array([[1, 0, 0],
       [1, 1, 0],
       [3, 1, 2]])

#Practice

1. Given the linear combinatioin below, try to create a corresponding matrix represening it.

:$$\theta = 5x + 3y - z$$


2. Given the system og linear combinations below, try to encode it as a matric. Also decribe the matrix.

$$
A = \left\{\begin{array}
5x_1 + 2x_2 +x_3\\
4x_2 - x_3\\
10x_3
\end{array}\right.
$$


3. Given the matrix below, express it as a linear combination in a markdown and a LaTeX markdown


In [56]:
G = np.array([
    [1,7,8],
    [2,2,2],
    [4,6,7]
])


4. Given the matrix below, display the output as a LaTeX markdown also express it as a system of linear combinations.


In [57]:
H = np.tril(G)
H


array([[1, 0, 0],
       [2, 2, 0],
       [4, 6, 7]])

In [58]:
I = np.tril(G)
I

array([[1, 0, 0],
       [2, 2, 0],
       [4, 6, 7]])

Algebra

In [60]:
C = np.array ([
               [1,2],
               [4,3],
               [2,0]
])
B = np.array([
              [6,7],
              [8,6],
              [8,9]
])
C+B

array([[ 7,  9],
       [12,  9],
       [10,  9]])

In [61]:
3 + B

array([[ 9, 10],
       [11,  9],
       [11, 12]])

#Subraction

In [62]:
C = np.array ([
               [1,2],
               [4,3],
               [2,0]
])
B = np.array([
              [6,7],
              [8,6],
              [8,9]
])
C-B

array([[-5, -5],
       [-4, -3],
       [-6, -9]])

In [63]:
3-B

array([[-3, -4],
       [-5, -3],
       [-5, -6]])

#Element-wise Multiplication

In [64]:
C*B
np.multiply(C,B)

array([[ 6, 14],
       [32, 18],
       [16,  0]])

In [65]:
2*B

array([[12, 14],
       [16, 12],
       [16, 18]])